============================= test session starts ==============================
platform linux2 -- Python 2.7.18, pytest-4.6.9, py-1.8.1, pluggy-0.13.0
rootdir: /home/sqared2
collected 0 items

=============================== warnings summary ===============================
/usr/lib/python2.7/dist-packages/_pytest/cacheprovider.py:134
  /usr/lib/python2.7/dist-packages/_pytest/cacheprovider.py:134: PytestCacheWarning: cache could not write path /home/sqared2/.pytest_cache/v/cache/stepwise
    self.warn("cache could not write path {path}", path=path)

/usr/lib/python2.7/dist-packages/_pytest/cacheprovider.py:134
  /usr/lib/python2.7/dist-packages/_pytest/cacheprovider.py:134: PytestCacheWarning: cache could not write path /home/sqared2/.pytest_cache/v/cache/nodeids
    self.warn("cache could not write path {path}", path=path)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========================== 2 warnings in 0.00 seconds ==========================
ERROR: file not found: pytest

